language: rust
sudo: true
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: osx
      rust: 1.33.0
      install:
        - cargo fmt --version || rustup component add rustfmt-preview
        - cargo clippy --version || rustup component add clippy-preview
      env: SUITE=ci
    - rust: 1.33.0
      addons:
        apt:
          packages:
            - git
            - autoconf
            - flex
            - bison
            - texinfo
            - libtool
      env: SUITE=ci-quick
    - rust: 1.33.0
      addons:
        apt:
          packages:
            - git
            - build-essential
      env: SUITE=ci-asm
    - rust: 1.33.0
      addons:
        apt:
          packages:
            - git
            - build-essential
      env: SUITE=ci-jit
    - os: osx
      rust: 1.33.0
      addons:
        apt:
          packages:
            - git
            - build-essential
      env: SUITE=ci-jit

script:
- make "$SUITE"

before_cache:
- rm -rf $HOME/.cargo/registry
